name: "Pre-release"

on: [push]

jobs:
  build: 
    name: "Build"  
    runs-on: windows-latest 
    steps:
      ##CHECKOUT
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Add source
        run: |
            dotnet nuget add source "https://nuget.bepinex.dev/v3/index.json" --name baget 

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore QuickPing.sln

      - name: Build Solution
        run: |
          msbuild.exe QuickPing.sln /p:platform="Any CPU" /p:configuration="Release"
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      ##CHECKOUT

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      ##DOTNET SETUP 3.0.x
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
          
      - name: Extract owner and repo
        uses: jungwinter/split@v1
        id: repo
        with:
          seperator: '/'
          msg: ${{ github.repository }}
          
      - name: Allow Unsecure
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV          
      - name: "Build & test"
        run: |
          echo "unsecure done!"
          
      ##GitVersion SETUP
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
            versionSpec: '5.x'
          
      ##GitVersion EXECUTE
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15
        id: gitversion
        with:
          useConfigFile: true
          updateAssemblyInfo: true
          updateAssemblyInfoFilename: QuickPing/Properties/AssemblyInfo.cs

      ##GitRelease SETUP
      - uses: gittools/actions/gitreleasemanager/setup@v0.9.15
        name: Install GitReleaseManager
        with:
          versionSpec: '0.12.x'
        
        
      ##GitRelease CREATE
      - name: Create release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/create@v0.9.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ steps.repo.outputs._0 }}
          repository: ${{ steps.repo.outputs._1 }}
          milestone: ${{ steps.gitversion.outputs.majorMinorPatch }}
          name: 'Pre-Release ${{ steps.gitversion.outputs.semVer }}'
          isPreRelease: true
          assets:  |
            QuickPing/Package/plugins/QuickPing.dll
           
      ##GitRelease PUBLISH 
      - uses: gittools/actions/gitreleasemanager/publish@v0.9.15
        name: Publish release with GitReleaseManager
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            owner: ${{ github.actor }}
            repository: ${{ github.event.repository.name }}
            tagName: ${{ steps.gitversion.outputs.semVer }}          
