name: "Release"

on:
  pull_request:
    branches: 
      - 'master'   
    types: 
      - closed


jobs:

  generate-changelog:
    name: "Generate Changelog"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    
      ##CHECKOUT
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      ##CHANGELOG
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          output: QuickPing/Package/CHANGELOG.md
          onlyLastTag: true
          includeLabels: |
                  "Bug"
                  "Enhancement"
                  "Breaking Change"
                  "Feature"
          excludeLabels: |
                  "wontfix"
                  "duplicate"
                  "Question"
                  "Good First Issue"
                  "Documentation"
                  "Help Wanted"
                  "invalid"
          breakingLabel: "Breaking Change"
          enhancementLabel: "Enhancement"
          bugsLabel: "Bug"
          
      - name: Archive changelog
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: QuickPing/Package/CHANGELOG.md
        
  build: 
    name: "Build and Deploy"  
    needs: generate-changelog
    runs-on: windows-latest 
    steps:
      # CHECKOUT
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Setups
      ##############
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      ##############
        
      # Add bepinex package source
      - name: Add source
        run: |
            dotnet nuget add source "https://nuget.bepinex.dev/v3/index.json" --name baget 

      # Useless?
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore QuickPing.sln

      - name: Build Solution
        run: |
          msbuild.exe QuickPing.sln /p:platform="Any CPU" /p:configuration="Release"
          
          
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - uses: ncipollo/release-action@v1
        with:
          artifacts: QuickPing/Package/plugins/*.dll
          generateReleaseNotes: true
          # bodyFile: QuickPing/Package/CHANGELOG.md
          commit: ${{ steps.branch-name.outputs.current_branch }}
          tag: ${{ env.GitVersion_MajorMinorPatch }}
          updateOnlyUnreleased: true
          name: "Release: ${{ env.GitVersion_SemVer }}"



