name: "Tagged-release"

on:
  push:
    tags:
      - "*.*.*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Build & test"
        run: |
          echo "done!"
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
        versionSpec: '5.x'
          
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          updateAssemblyInfo: true
